### ISSUE TITLE
ImportError: cannot import name 'Client' from 'hubble'

### ISSUE THREAD

**Issue by ct1976** [yuanjie-ai/ChatLLM#2]
ImportError: cannot import name 'Client' from 'hubble'

**Comment by feiyuntaoist** [comment]
我也是这个错误
C:\myprogs\python38\python.exe C:\mycodes\ChatLLM\chatllm\applications\chatpdf.py 
Traceback (most recent call last):
  File "C:\mycodes\ChatLLM\chatllm\applications\chatpdf.py", line 15, in <module>
    from chatllm.applications.chatann import ChatANN
  File "C:\mycodes\ChatLLM\chatllm\applications\chatann.py", line 13, in <module>
    from chatllm.embedding import SentenceEmbedding
  File "C:\mycodes\ChatLLM\chatllm\embedding.py", line 12, in <module>
    from meutils.docarray_ import Document, DocumentArray
  File "C:\myprogs\python38\lib\site-packages\meutils\docarray_\__init__.py", line 6, in <module>
    from meutils.docarray_.array import DocumentArray
  File "C:\myprogs\python38\lib\site-packages\meutils\docarray_\array\__init__.py", line 1, in <module>
    from meutils.docarray_.array.document import DocumentArray
  File "C:\myprogs\python38\lib\site-packages\meutils\docarray_\array\document.py", line 5, in <module>
    from meutils.docarray_.array.mixins import AllMixins
  File "C:\myprogs\python38\lib\site-packages\meutils\docarray_\array\mixins\__init__.py", line 18, in <module>
    from meutils.docarray_.array.mixins.io.pushpull import PushPullMixin
  File "C:\myprogs\python38\lib\site-packages\meutils\docarray_\array\mixins\io\pushpull.py", line 9, in <module>
    from hubble import Client as HubbleClient
ImportError: cannot import name 'Client' from 'hubble' (C:\myprogs\python38\lib\site-packages\hubble\__init__.py)

我的系统配置：
windowns 10专业版
python3.8.10
32G内存，无GPU。

**Comment by yuanjie-ai** [comment]
系统兼容的问题，明天修复下。

**Comment by yuanjie-ai** [comment]
已修复，欢迎测试。
