### ISSUE TITLE
ImportError: cannot import name 'clear_cuda_cache' from 'meutils.decorators' 

### ISSUE THREAD

**Issue by cristianohello** [yuanjie-ai/ChatLLM#4]
Traceback (most recent call last):
  File "/root/autodl-tmp/chatglm/ChatLLM-master/zystest.py", line 2, in <module>
    from chatllm.applications import ChatBase
  File "/root/autodl-tmp/chatglm/ChatLLM-master/chatllm/applications/__init__.py", line 11, in <module>
    from chatllm.applications.chatbase import ChatBase
  File "/root/autodl-tmp/chatglm/ChatLLM-master/chatllm/applications/chatbase.py", line 12, in <module>
    from meutils.decorators import clear_cuda_cache
ImportError: cannot import name 'clear_cuda_cache' from 'meutils.decorators' (/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/meutils/decorators/__init__.py)

**Comment by yuanjie-ai** [comment]
更新下meutils



发自我的iPhone


------------------ Original ------------------
From: cristianohello ***@***.***&gt;
Date: Thu,May 4,2023 3:28 PM
To: yuanjie-ai/ChatLLM ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [yuanjie-ai/ChatLLM] ImportError: cannot import name'clear_cuda_cache' from 'meutils.decorators'  (Issue #4)





 
Traceback (most recent call last):
 File "/root/autodl-tmp/chatglm/ChatLLM-master/zystest.py", line 2, in 
 from chatllm.applications import ChatBase
 File "/root/autodl-tmp/chatglm/ChatLLM-master/chatllm/applications/init.py", line 11, in 
 from chatllm.applications.chatbase import ChatBase
 File "/root/autodl-tmp/chatglm/ChatLLM-master/chatllm/applications/chatbase.py", line 12, in 
 from meutils.decorators import clear_cuda_cache
 ImportError: cannot import name 'clear_cuda_cache' from 'meutils.decorators' (/root/miniconda3/envs/chatglm20230401/lib/python3.9/site-packages/meutils/decorators/init.py)
